---

- name: ensure qemu-guest-agent is installed
  apt:
    name: qemu-guest-agent
    state: present

- name: start qemu-guest-agent
  systemd:
    state: restarted
    name: qemu-guest-agent
    enabled: yes
